### ISSUE TITLE
As an user, I want to see navs

### ISSUE THREAD

**Issue by abemscac** [abemscac/inet-meow0516#2]
身為一個使用者，我想要看到上方和左方的選單

![Screen Shot 2022-04-21 at 9 01 52 AM](https://user-images.githubusercontent.com/59676941/164350961-01476562-5c74-42ae-ad1c-328e2e4f8279.png)

**備註：**
這是一個feature，他底下會有多個implementation-story
真正可以被實踐的東西是implementation-story，feature是他們的parent，主要是用來描述這個大功能的全貌，然後追蹤底下的issue
例如說要造一輛車我們會需要方向盤、輪胎、引擎等等
「造車子」就會是一個feature，實作輪胎、實作方向盤、實作引擎就會是implementation-story
所以我們不會有`2-navs`這樣的branch，因為feature是抽象的，真正有實體的東西是他底下的那些implementation-story
正常的結構會是epic -> feature -> implementation-story
但是我們的功能小，epic對我們來說太大了，所以feature就夠了

- [x] #3 
- [x] #4

**Comment by abemscac** [comment]
@meow0516 yo阿姨
您下一個要做的issue會4這e格，會開始有style的出現
您想要用哪一種style都可以，`scss`/`postcss`(跟scss差不多)/`utility-first css`(tailwind或primeflex這種的)/`styled-component`
您可以挑一個中意的或想學的來用

另外共用元件也會開始出現，例如navbar上面的input
但是您不見得要馬上把它做成共用的component
因為他現在只有出現一次，所以您可以直接把它寫在navbar裡面
我們永遠可以藉由重構程式碼來把那些東西從非共用轉成共用
我發現這樣的開發速度會快一些，不會過度設計/過度思考
就算您知道這個input最後會需要5個props，但是現在只用到2個
可以只做用到的那2個就好，另外3個等真正用到了再來refactor，會讓事情變得比較簡單
不過這只是建議，如果這些東西對您來說其實挺容易的那也可以一次把它做完，完全沒問題

**Comment by abemscac** [comment]
關於一些github workflow branch的管理知識，供您參考

您可以隨意刪除自己在remote建立的branch，Sourcetree的話刪除的時候要勾Force delete+Delete remote branch
只要確定其他人沒有在用那個branch就好
因為通常implementation story會拆成很小，一次由一個人負責
所以其他人通常不會碰到您建立的branch，除非您把那個issue它交給其他人接手

有人習慣在功能還沒開發完成前把branch取叫`1-create-project-wip`或是`1-create-project-2`
等功能做完之後再推真正的`1-create-project`到remote，最後把那個暫時的-wip或是-2從remote刪掉
看您自己喜歡哪一種，大原則就是您自己建立的branch要怎麼搞都可以，不會有問題

**Comment by abemscac** [comment]
@meow0516 yo阿姨
Patrick哥說他照著這篇的做 https://github.com/typicode/husky/issues/390#issuecomment-762213421 之後有成功解決搜死tree跟husky沒辦法一起用的問題
我沒試過，但是供您參考

**Comment by meow0516** [comment]
Y，哈士奇和樹目前看起來能和平相處了
