### ISSUE TITLE
Navs for guests

### ISSUE THREAD

**Issue by abemscac** [abemscac/inet-meow0516#3]
樣板: https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=74%3A807

![Screen Shot 2022-04-21 at 9 01 52 AM](https://user-images.githubusercontent.com/59676941/164350961-01476562-5c74-42ae-ad1c-328e2e4f8279.png)

請注意，這個issue只需要做遊客的navs。

**目標**

- [x] 在桌面尺寸，上方navbar會出現：
  - logo
  - 搜尋欄位 ([Input](https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=37%3A116)元件)
  - 登入按鈕 ([Button](https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=1%3A22)元件)
  - 註冊按鈕
- [x] 在行動尺寸，上方navbar會出現：
  - 開啟左側選單按鈕
  - logo
  - 搜尋欄位
  - 開啟遊客dropdown的按鈕
- [x] 左側選單裡面會出現：
  - 登入按鈕
  - 註冊按鈕
  - 討論板列表
- [x] 左側選單開啟時背景應該要變黑。
- [x] 遊客dropdown([Dropdown](https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=37%3A366)元件)裡面會出現：
  - 註冊選項
  - 登入選項

**Comment by meow0516** [comment]
@abemscac figma看不到文件耶：Either this file doesn’t exist or you don’t have permission to view it.

**Comment by abemscac** [comment]
@meow0516 Hi 阿姨

這可能是因為您還沒有加入那個figma team
aka 您還沒有權限
aka 您不夠格看
aka 您連看文件的資格都沒有

建議的解決方法：
- 自己寫一個，或是
- 到上次那個repository https://github.com/abemscac/inet-rest-api#resource-urls 找到ㄈ1格馬的邀請函，加入team之後應該就可以看見了
